name: Laravel CI/CD with Makefile and GitHub Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql-test:
        image: mysql:8
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpunit, mysql

      # Install dependencies
      - name: Install Dependencies
        run: make install

      # Set up environment
      - name: Configure .env
        run: |
          cp .env.example .env
          php artisan key:generate
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql-test/' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=test_db/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=test_user/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=test_password/' .env

      # Run migrations
      - name: Run Migrations
        run: php artisan migrate --no-interaction --force

      # Run tests
      - name: Run Tests
        run: vendor/bin/phpunit --testdox
