name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24
        options: --privileged

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Use the PHP version your Laravel app requires
          tools: composer, phpunit, mysql

      # Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      # Set up Laravel environment
      - name: Set Environment Variables
        run: cp .env.example .env

      # Generate application key
      - name: Generate App Key
        run: php artisan key:generate

      # Run migrations
      - name: Run Migrations
        run: php artisan migrate --no-interaction --force

      # Run tests
      - name: Run Tests
        run: vendor/bin/phpunit --testdox

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     # Build Docker Image
  #     - name: Build Docker Image
  #       run: docker build -t laravel-app .

  #     # Push Docker Image to Docker Hub
  #     - name: Push Docker Image to Docker Hub
  #       run: |
  #         echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
  #         docker tag laravel-app:latest bullguchev/laravel-app:latest
  #         docker push bullguchev/laravel-app:latest
